name: smart_student_planner
description: A Smart Student Planner App for managing academic activities.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0                      # Local SQLite database
  path: ^1.8.3                          # File path helper
  shared_preferences: ^2.2.2            # Save user settings/theme
  flutter_local_notifications: ^17.0.0  # Reminder notifications
  provider: ^6.1.1                      # State management
  intl: ^0.19.0                         # Date formatting
  percent_indicator: ^4.2.3             # Progress circles
  animate_do: ^3.3.4                    # Beautiful animations
  google_fonts: ^6.1.0                  # Stylish fonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true